### ISSUE TITLE
Ruby 3.1対応

### ISSUE THREAD

**Issue by mtgto** [labocho/rubydoc-ja-docsets#94]
http://labocho.github.io/rubydoc-ja-docsets/ にRuby 3.1がまだないようなので追加お願いします 🙇

----

いつも大変重宝させていただいております 🙏

**Comment by labocho** [comment]
忘れてました！
Ruby 3.1 のドキュメント追加しました。
http://labocho.github.io/rubydoc-ja-docsets/

> いつも大変重宝させていただいております 🙏

うれしいです！ありがとうございます！

**Comment by mtgto** [comment]
ありがとうございます 🎉
